project:
  goal: "i want to do skin cancer classification using deep learning"
  title: ""

dataset:
  kind: imagefolder
  name: default
  path: data/dataset
  splits:
    train: train
    val: val
    test: test
  allow_fallback: false
  allow_download: false
  val_fraction: 0.1

research:
  num_problems: 2
  num_objectives: 2
  num_contributions: 2
  num_questions: 1

llm:
  provider: openai
  model: glm-4.5
  chat_url: https://api.z.ai/api/coding/paas/v4/chat/completions
  api_key_env: ZAI_API_KEY
  default: ""
  custom: ""
  use: default
  stream: true
  strict: true
  allow_custom_openai_models: true
  retry:
    max_tries: 4
    backoff_initial: 2
    backoff_max: 60

embeddings:
  enable: true
  provider: huggingface
  model: google/embeddinggemma-300m
  dtype: float16
  batch_size: 2
  max_length: 1024
  content: both
  aggregate: none
  cache: true
  retrieval:
    enable: true
    index: faiss-cpu
    top_k: 8
    min_sim: 0.3

telemetry:
  enable_latency_html: true
  enable_stage_histograms: true
  enable_cost_summary: true
  budgets:
    enable: false
    max_cost_usd: 0.0
    max_tokens: 0

pipeline:
  always_fresh: true
  max_iters: 2
  skip:
    find_papers: true
    summaries: true
    novelty: false
    idea_blueprints: false
    planner: false
    iterate: false
    lit_review: false
    interactive: false
  orchestrator:
    phase_steps: 2
    personas:
      enable: false
  write_paper: false
  write_paper_llm:
    enable: false
    min_words: 12000
    request_timeout: 900
    request_retries: 4
    section_min_paragraphs:
      Introduction: 4
      Related Work: 8
      Methodology: 8
      Experimental Setup: 3
      Results: 8
      Discussion: 8
      Conclusion: 2
  write_paper_style:
    referent: "This study"
    page_reminder_after_intro: true

  summarize:
    llm: default
    model: ""
    max_pages: 0
    max_chars: 0
    pass1_chunk: 120000
    progress: true
    detail: true
    save_raw: false
    print_raw: true
    force_chunk: false
    skip_existing: false
    num_workers: 2
    timeout: 60
    timeout_full: 180
    max_tries: 4
    enforce_required: true
    fill_not_mentioned: true
    stream: true

  novelty:
    llm: default
    model: ""
    stream: true
    print_progress: true
    request_timeout: 60
    sampling:
      temperatures: [0.2]
    personas:
      enable: true
      steps: 4
      print: true
      debate:
        enable: true
        rounds: 2
        roles: [PhD, PhD, Professor, Professor, Postdoc, Postdoc]
        until_agree: true
    uniqueness:
      enable: true
    detailed_ideas: true
    only_ideas: false
    scoring:
      diversity: true
      diversity_weight: 0.3
      similarity_threshold: 0.85
    clustering:
      enable: false
      method: kmeans
      k_min: 3
      k_max: 6

  planner:
    llm: default
    model: ""
    request_timeout: 60
    request_retries: 2
    personas:
      enable: true

  iterate:
    llm: default
    model: ""
    personas:
      enable: true

  codegen:
    enable: true
    llm: default
    model: ""
    editor:
      enable: true
      llm: default
      model: ""
    structured:
      enable: true
      use_plan_requirements: true
      auto_commit: false
      temperature: 0.2
      deterministic:
        seed: 1337
      sandbox:
        timeout: 45
      branch_prefix: codegen

  idea_blueprints:
    llm: default
    model: ""
    top_k: 3

  interactive:
    enable: false
    max_steps: 10
    target_delta: 0.01

  hitl:
    confirm: false
    auto_approve: true

  personas:
    llm: default
    model: ""

  find_papers:
    query: ""
    page_size: 100
    allowed_years: ["2023", "2024", "2025"]
    download_oa_only: true
    max_kept: 40
    backup: arxiv
    expand:
      include_terms: []
      synonyms: []
    relevance:
      enable: false
    llm_query:
      enable: true
      count: 4
      max_len: 120
    provider: arxiv
    arxiv:
      categories: []
      max_results_per_query: 10
      keywords: []
      keyword_query:
        enable: true
        terms_per_query: 1
        max_queries: 5
        fields: ["ti", "abs"]
        simple: true

# Tier-1 validator (optional)
tier1:
  enable: false

pdf:
  backend: pypdf
  ocr: false
