# Project settings that override env/defaults across agents.
# You can rename or point CONFIG_FILE to a different path.

project:
  # Only prompt override: the goal (domain-agnostic)
  goal: "i want to do skin cancer classification and detection using deep learning model"
  # Optional explicit title (used in paper/report); leave empty to auto-generate
  title: ""

dataset:
  # Generalized dataset configuration (YAML-first). If absent, env may be used as fallback.
  # kind: imagefolder | cifar10 | custom (optional; inferred when omitted)
  kind: imagefolder
  # Free-form label; does not gate behavior
  name: default
  # Base path; for imagefolder expects split subfolders
  path: data/dataset
  # Optional split folder names
  splits:
    train: train
    val: val
    test: test
  # Allow safe fallbacks (e.g., torchvision FakeData) if real dataset not present.
  allow_fallback: false
  # Allow dataset download where supported (e.g., CIFAR10)
  allow_download: false
  # For CIFAR10 only: fraction of train data used as validation
  val_fraction: 0.1
  # Optional custom dataset classes when kind=custom
  # custom:
  #   train: { module: mypkg.datasets, class: MyTrain, kwargs: { root: /data, split: train } }
  #   val:   { module: mypkg.datasets, class: MyVal,   kwargs: { root: /data, split: val } }
  #   test:  { module: mypkg.datasets, class: MyTest,  kwargs: { root: /data, split: test } }

research:
  num_problems: 2
  num_objectives: 2
  num_contributions: 2
  num_questions: 1

# Global LLM profiles and default selection
llm:
  # Aliases map to providers via utils.llm_utils
  default: gpt-5-mini   # OpenAI GPT‑5 mini
  custom: deepseek      # DeepSeek chat
  use: default          # fallback profile when per-agent is omitted
  # Streaming toggle for LLM calls (chat_text and chat_json)
  stream: true

# Pipeline controls (YAML-first). All are optional.
pipeline:
  # Skip stages automatically without CLI or env flags
  skip:
    find_papers: true
    summaries: true
    novelty: true
    idea_blueprints: false
    planner: true
    iterate: false
    lit_review: true
    interactive: false
  # Number of iterate cycles (fallback to 2 if unset)
  max_iters: 2
  # Write paper draft at the end
  write_paper: false
  # Re-run stages even if artifacts already exist
  always_fresh: true
  # Summarize agent configuration
  summarize:
    llm: default          # profile alias
    # Optional explicit model override for summarize; empty uses profile default
    model: ""
    max_pages: 0          # 0 = no page limit
    max_chars: 0          # 0 = no character limit
    pass1_chunk: 120000    # chars per chunk when chunking
    progress: true        # print high-level progress lines
    detail: true         # print timing/details
    save_raw: false       # save intermediate JSON files (*.pass1.json, *.merged.json, ...)
    print_raw: true       # print final LLM JSON (pre-validate) to console
    force_chunk: false    # force chunking instead of full-text pass
    # Timeouts/retries (seconds/attempts). Full-text often needs longer.
    timeout: 60           # per-call timeout for chunked requests
    timeout_full: 180     # per-call timeout for full-text request
    max_tries: 4          # retry attempts on 429/5xx/transient errors
    # Enforce required presence of training knobs/metrics/dataset_details
    enforce_required: true
    # Fill missing fields with a clear note instead of blanks
    fill_not_mentioned: true
    # Per-stage streaming toggle
    stream: true

  # Novelty agent configuration
  novelty:
    llm: default
    # Per-stage streaming toggle
    stream: true
    personas:
      enable: true
      steps: 4
      print: true
      debate:
        enable: true
        rounds: 2
        roles: [PhD, PhD, Professor, Professor, Postdoc, Postdoc]
        until_agree: true
        # max_rounds: 0  # 0 → auto-cap
    uniqueness:
      enable: true

  # Planner agent configuration
  planner:
    llm: default
    personas:
      enable: true

  # Iterate agent configuration
  iterate:
    llm: default
    personas:
      enable: true    # optional persona notes for iterate (off by default)

  # Code generation controls
  codegen:
    enable: true      # LLM-driven augmentation module generation
    llm: default
    editor:
      enable: true    # Optional REPLACE/EDIT training hooks generation
      llm: default

  # Idea blueprints agent
  idea_blueprints:
    llm: default
    top_k: 3

  # Optional interactive stage
  interactive:
    enable: false

  # Human-in-the-loop confirmation gates
  hitl:
    confirm: false
    auto_approve: true
